apiVersion: apps/v1
kind: Deployment
metadata:
  name: techops-demo
  namespace: demo
  labels:
    app: techops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techops-demo
  template:
    metadata:
      labels:
        app: techops-demo
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: html
          configMap:
            name: techops-demo-html
