apiVersion: v1
kind: Service
metadata:
  name: techops-demo
  namespace: demo
  labels:
    app: techops-demo
spec:
  type: NodePort
  selector:
    app: techops-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
